version: '3.8'
name: "nest"

services:
  postgres:
    image: postgres:16-alpine
    container_name: nestdb
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:
